# This file contains values from Cookiecutter

default_context:
  project_name: "streamlit-project-template"
  project_description: "A streamlit project template"
  organization: "tuhinmallick"
  license: "MIT"
  minimal_python_version: 3.8
  github_name: "tuhinmallick"
  email: "tuhin.mllk@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
